# Generated by Django 6.1.1 on 2026-10-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_DB',
            fields=[
                ('Name', models.CharField(max_length=10)),
                ('Mobile', models.IntegerField()),
                ('Address', models.TextField()),
                ('No_Plate', models.CharField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('Vehicle_model', models.CharField()),
                ('Damage_percentage', models.FloatField()),
            ],
        ),
    ]
